/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ERC20 } from "./ERC20";
export type { ERC20Burnable } from "./ERC20Burnable";
export type { IERC20Metadata } from "./IERC20Metadata";
export type { IERC20 } from "./IERC20";
export type { IClaimManager } from "./IClaimManager";
export type { Staking } from "./Staking";

export { ERC20__factory } from "./factories/ERC20__factory";
export { ERC20Burnable__factory } from "./factories/ERC20Burnable__factory";
export { IERC20Metadata__factory } from "./factories/IERC20Metadata__factory";
export { IERC20__factory } from "./factories/IERC20__factory";
export { IClaimManager__factory } from "./factories/IClaimManager__factory";
export { Staking__factory } from "./factories/Staking__factory";
