name: Pull Request
on:
  pull_request:

jobs:
  install_packages:
    name: Warm-up packages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v2-beta
        with:
          node-version: 14.x
          registry-url: https://registry.npmjs.org/
      - name: Install nx
        run: npm install -g nx
      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: fe-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
  sol_tests:
    needs:
      - install_packages
    name: Sol tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
  fe_e2e_tests:
    needs:
      - install_packages
    name: Frontend E2E tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v2-beta
        with:
          node-version: 14.x
          registry-url: https://registry.npmjs.org/
      - name: Install nx
        run: npm install -g nx
      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: fe-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: npm run ci:e2e:fe
  fe_tests:
    needs:
      - install_packages
    name: Frontend tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v2-beta
        with:
          node-version: 14.x
          registry-url: https://registry.npmjs.org/
      - name: Install nx
        run: npm install -g nx
      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: fe-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
      - name: Install dependencies
        run: npm install
      - name: Lint
        run: npm run lint:fe
      - name: Build
        run: npm run build:fe
      - name: Test
        run: npm run test:fe
