name: Pull Request
on:
  pull_request:

jobs:
  sol_tests:
    name: Sol tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
  fe_e2e_tests:
    name: Frontend E2E tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v2-beta
        with:
          node-version: 14.x
          registry-url: https://registry.npmjs.org/
      - name: Update NPM
        run: npm i -g npm@latest
      - name: Install nx
        run: npm install -g nx
      - name: Install Linux SWC
        run: npm i @next/swc-linux-x64-gnu --no-save
      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: fe-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: npm run ci:e2e:fe
  fe_tests:
    name: Frontend tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v2-beta
        with:
          node-version: 14.x
          registry-url: https://registry.npmjs.org/
      - name: Update NPM
        run: npm i -g npm@latest
      - name: Install nx
        run: npm install -g nx
#      - name: Install Linux SWC
#        run: npm i @next/swc-linux-x64-gnu --no-save
      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: fe-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
      - name: Install dependencies
        run: npm ci
      - name: Lint
        run: npm run lint:fe
      - name: Build
        run: npm run build:fe
      - name: Test
        run: npm run test:fe
